import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";

export const metadata: Metadata = {
  title: "ToDo App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: '400'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt" className={poppins.className}>
      <body>{children}</body>
    </html>
  );
}
